name: Abubakar

on:
    push:
        branches:
            - main

jobs:
    job-name:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo Hello world!

