name: Example Workflow

on: [push]

jobs:
  job-with-name:
    name: 🛠 Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This job has a custom name!"

  job-without-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This job will show its ID as the name"
