name: Abubakar Actions Again

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    this-is-a-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: "us-east-1"
            
            - name: Set up Terraform CLI
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform Format
              run: terraform fmt

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.30.0
              with:
                scan-type: 'fs'
                scan-ref: '.'


            - name: Setup TFLint
              uses: terraform-linters/setup-tflint@v4
            
            - name: Run TFLint
              run: tflint -f compact

            - name: Terraform Plan
              run: terraform plan
            

            


            