name: Abubakar

on:
    push:
        branches:
            - main

jobs:
    my_first_job:
        name: My first job
        runs-on: ubuntu-latest
        steps:
            - run: echo Hello World!
        




